[package]
name = "polspec"
version = "0.1.0"
edition = "2024"

[lib]
name = "_polspec"
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = "thin"

[dependencies]
polars = { version = "0.55.2", features = [
    "dtype-categorical",
    "dtype-i8",
    "dtype-i16",
    "dtype-u8",
    "dtype-u16",
] }
polars-core = { version = "0.55.2", features = [
    "dtype-i8",
    "dtype-i16",
    "dtype-u8",
    "dtype-u16",
] }
pyo3 = { version = "0.29.2", features = ["extension-module", "abi3-py311"] }
pyo3-polars = { version = "0.28.0", features = [
    "dtype-categorical",
    "dtype-full",
] }
rand = { version = "0.8" }
rand_distr = "0.4"
rand_xoshiro = "0.6"
rayon = "1.12.0"
