"""`polspec test`: a pytest round-trip test from a spec.

The one verb that writes code rather than data. What it emits is the
round-trip `tests/test_roundtrip.py` pins for polspec itself, applied to the
user's own spec -- with the checks generation cannot satisfy switched off and
a comment saying why, rather than a test the CLI already knows will fail.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from polspec import FrameSpec
from polspec.cli._io import (
    _display_path,
    _loaded_specs,
    _maybe_format,
    _relative_to_output,
    _snake_case,
)
from polspec.errors import CliError


def _skip_reasons(spec_cls: type[FrameSpec]) -> tuple[dict[str, bool], list[str]]:
    """validate() flags to disable, and why, so the generated test can pass.

    generate() does not attempt __checks__ or ColSpec.validators -- see
    docs/explanation/limitations.md. A round-trip test that did not account for
    this would simply fail on any spec using them, so the flag each
    constraint needs is disabled with a comment explaining why, rather than
    emitting a test the CLI already knows will not pass.

    `unique=True` and `__unique_together__` used to be on that list. They are
    generated now, so the generated test validates them like anything else.
    """
    flags: dict[str, bool] = {}
    reasons: list[str] = []

    if spec_cls.spec.checks:
        flags["validate_checks"] = False
        reasons.append(
            "__checks__ wraps arbitrary expressions that generation cannot "
            "be made to satisfy"
        )

    if any(c.validators for c in spec_cls.spec.columns.values()):
        flags["validate_validators"] = False
        reasons.append(
            "ColSpec.validators wraps arbitrary expressions that generation "
            "cannot be made to satisfy"
        )

    if any(c.pattern is not None for c in spec_cls.spec.columns.values()):
        flags["validate_pattern"] = False
        reasons.append(
            "ColSpec.pattern is checked by validation only; generation fills "
            "the column with ordinary random text (use format= for a shape "
            "polspec can generate)"
        )

    return flags, reasons


def _render_test_case(
    class_name: str,
    spec_cls: type[FrameSpec],
    *,
    rows: int,
    seed: int,
    cartesian: bool,
) -> str:
    fn_name = _snake_case(class_name)
    cross_spec_fks = [
        fk for fk in spec_cls.spec.foreign_keys if fk.references != "self"
    ]

    if cross_spec_fks:
        names = ", ".join(repr(fk.name) for fk in cross_spec_fks)
        return (
            f"@pytest.mark.skip(\n"
            f"    reason=(\n"
            f'        "{class_name} has foreign key(s) {names} referencing another "\n'
            f'        "FrameSpec. generate()/validate() need a parent DataFrame via "\n'
            f'        "references={{OtherSpec: parent_df}} -- see "\n'
            f'        "docs/how-to/constraints.md#referential-integrity-foreignkey."\n'
            f"    )\n"
            f")\n"
            f"def test_{fn_name}_roundtrip():\n"
            f"    pass\n"
        )

    flags, reasons = _skip_reasons(spec_cls)
    kwargs = "".join(f", {name}={value}" for name, value in flags.items())
    comment = "".join(f"    # {reason}\n" for reason in reasons)

    lines = [
        f"def test_{fn_name}_roundtrip():\n",
        (
            f"{comment}"
            f"    df = {class_name}.generate({rows}, seed={seed})\n"
            f"    {class_name}.validate(df{kwargs})\n"
        ),
    ]
    if cartesian and _supports_cartesian(spec_cls):
        lines.append(
            f"\n\ndef test_{fn_name}_cartesian_coverage():\n"
            f"{comment}"
            f'    df = {class_name}.generate({rows}, method="cartesian", seed={seed})\n'
            f"    {class_name}.validate(df{kwargs})\n"
        )
    elif cartesian:
        lines.append(
            f'\n\n# No cartesian-coverage test: method="cartesian" needs at least one\n'
            f"# Enum, Boolean, or bounded numeric column to build coverage from, and\n"
            f"# {class_name} has none.\n"
        )
    return "".join(lines)


def _supports_cartesian(spec_cls: type[FrameSpec]) -> bool:
    """Whether `method="cartesian"` has anything to build coverage from.

    Rather than re-deriving `_coverage_values`' eligibility rule here (and
    risk it silently drifting from the real one), this asks the engine
    directly with a throwaway single-row generation.
    """
    try:
        spec_cls.generate(1, method="cartesian", seed=0)
    except ValueError:
        return False
    return True


_TEST_MODULE_HEADER = '''"""Generated by `polspec test {source}`.

Regenerate with:

    polspec test {source} -o {output}

This file is only overwritten by running that command again -- edit freely.
"""

from pathlib import Path

from polspec import FrameSpec

'''

_PY_LOADER_HELPER = """

def _load_spec_module(path):
    import importlib.util

    spec = importlib.util.spec_from_file_location(path.stem, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module
"""


def _cmd_test(args: argparse.Namespace) -> int:
    source = Path(args.source)
    if not source.exists():
        raise CliError(f"no such file: {source}")
    output = Path(args.output)

    specs = _loaded_specs(source, args.cls, output)

    parts = [
        _TEST_MODULE_HEADER.format(
            source=_display_path(_relative_to_output(source, output)),
            output=_display_path(str(output)),
        )
    ]
    if source.suffix.lower() == ".py":
        parts.append(_PY_LOADER_HELPER)
    if any(
        fk.references != "self"
        for _, spec_cls, _ in specs
        for fk in spec_cls.spec.foreign_keys
    ):
        parts.append("\nimport pytest\n")

    for class_name, spec_cls, loader_snippet in specs:
        parts.append(f"\n{loader_snippet}\n")
        parts.append(
            "\n\n"
            + _render_test_case(
                class_name,
                spec_cls,
                rows=args.rows,
                seed=args.seed,
                cartesian=not args.no_cartesian,
            )
        )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("".join(parts).rstrip() + "\n", encoding="utf-8")
    _maybe_format(output)

    print(f"Wrote {len(specs)} test spec(s) to {output}")
    return 0
